name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0 # Need to fetch all for proper history
            -   name: Collect build info
                id: info
                uses: actions/github-script@v6
                with:
                    script: |
                        let buildType = "Release";
                        core.setOutput("build_type", buildType);
                        let shortHash = "";
                        await exec.exec("git", ["rev-parse", "--short", "HEAD"], {
                            listeners: {
                                stdout: d => shortHash += d.toString().trim(),
                            }
                        });
                        core.setOutput("sha_short", shortHash);
                        core.setOutput("build_id", context.runNumber);
            -   uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: "9.0.x"
            -   name: Build
                run: |
                    ./build.sh --target Publish --build-type Release --build-id ${{ steps.info.outputs.build_id }} --nuget-api-key "${{ secrets.GITHUB_TOKEN }}" --nuget-source https://nuget.pkg.github.com/ResoniteModding/index.json
            -   name: Upload Artifacts
                uses: actions/upload-artifact@v4
                with:
                    path: "./bin/dist/*.zip"
                    name: "BepInEx_Release_${{ steps.info.outputs.sha_short }}_${{ steps.info.outputs.build_id || 0 }}"